import Providers from './GlobalRedux/provider';
import Footer from './components/Footer';
import Navbar from './components/Navbar';

import './globals.css';
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Providers>
        <div className="container">{children}</div>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
